name: stories_admin
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  stories_data:
    path: ../stories_data
  path_provider: ^2.1.5
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  go_router: ^15.1.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  dio: ^5.8.0+1
  meta: ^1.16.0
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.4.0
  get_it: ^8.0.3
  image_picker: ^1.1.2
  flutter_svg: ^2.0.16
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 


flutter:
  uses-material-design: true
  assets:
  - assets/test/
  - assets/icons/
  - .env
